spring:
  redis:
      host: 192.168.4.181
      password: ""
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-idle: 10
          max-active: 10
          min-idle: 1
      database: 0